import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/widgets/Footer/Footer";
import ReduxProvider from "@/app/ReduxProvider";
import AuthInit from "@/app/AuthInit";
import { ThemeProvider } from "@/shared/context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" data-theme="dark" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: `(function(){var t=localStorage.getItem('gc-theme');document.documentElement.setAttribute('data-theme',t==='light'?'light':'dark');})();` }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
      <ThemeProvider>
        <ReduxProvider>
            <AuthInit />
            {children}
        </ReduxProvider>
        <Footer />
      </ThemeProvider>
      </body>
    </html>
  );
}
