
const API_BASE_URL =
    process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:9005/api';

console.log('API_BASE_URL:', API_BASE_URL);

export const API_ENDPOINTS = {
    USER: {
        LOGIN: `${API_BASE_URL}/users/login`,
        LOGOUT: `${API_BASE_URL}/users/logout`,
        SEND_CODE: `${API_BASE_URL}/users/send-code`,
        REGISTRATION: `${API_BASE_URL}/users/register`,
        REFRESH: `${API_BASE_URL}/users/refresh`,
        GET_USERS: `${API_BASE_URL}/users/getAll`,
        GET_PROFILE: `${API_BASE_URL}/users/profile`,
        GET_MY_HISTORY: `${API_BASE_URL}/users/my-history`,
        GET_MY_TEST_HISTORY: `${API_BASE_URL}/users/my-test-history`,
GET_MY_REPORTS: `${API_BASE_URL}/users/my-reports`,
        GET_LEARNING_PLAN: `${API_BASE_URL}/users/learning-plan`,
        GET_ACTIVITY_HEATMAP: `${API_BASE_URL}/users/activity-heatmap`,
        GENERATE_TOPIC_GUIDE: `${API_BASE_URL}/users/topic-guide`,
        GET_ACHIEVEMENTS:     `${API_BASE_URL}/users/achievements`,
        UPDATE_USER: (id: number | string) => `${API_BASE_URL}/users/${id}`,
    },
    CHALLENGE: {
        CREATE: `${API_BASE_URL}/challenges/create`,
        VERIFY: `${API_BASE_URL}/challenges/verify`,
        GET_ALL: `${API_BASE_URL}/challenges/getAll`,
        GET_ONE: (id: number | string) => `${API_BASE_URL}/challenges/${id}`,
        UPDATE: (id: number | string) => `${API_BASE_URL}/challenges/${id}`,
        DELETE: (id: number | string) => `${API_BASE_URL}/challenges/${id}`,
        EXECUTE: (id: number | string) => `${API_BASE_URL}/challenges/${id}/execute`,
        FORMAT: `${API_BASE_URL}/challenges/format`,
        GET_HISTORY: (id: number | string) => `${API_BASE_URL}/challenges/${id}/history`,
        GET_SOLUTIONS: (id: number | string) => `${API_BASE_URL}/challenges/${id}/solutions`,
        GET_REVIEWS: (id: number | string) => `${API_BASE_URL}/challenges/${id}/reviews`,
        CREATE_REVIEW: (id: number | string) => `${API_BASE_URL}/challenges/${id}/reviews`,
        GET_TOPICS: `${API_BASE_URL}/challenges/topics`,
        CREATE_TOPIC: `${API_BASE_URL}/challenges/topics`,
        GET_REPORT_REASONS: (id: number | string) => `${API_BASE_URL}/challenges/${id}/report-reasons`,
        CREATE_REPORT: (id: number | string) => `${API_BASE_URL}/challenges/${id}/report`,
        AI_GENERATE: `${API_BASE_URL}/challenges/ai/generate`,
        AI_ANALYZE: (id: number | string) => `${API_BASE_URL}/challenges/${id}/ai/analyze`,
        AI_CHAT: (id: number | string) => `${API_BASE_URL}/challenges/${id}/ai/chat`,
    },
    ADMIN: {
        OVERVIEW:      `${API_BASE_URL}/admin/overview`,
        ACTIVITY:      `${API_BASE_URL}/admin/activity`,
        CHALLENGES:    `${API_BASE_URL}/admin/challenges`,
        USERS:         `${API_BASE_URL}/admin/users`,
        REPORTS:         `${API_BASE_URL}/admin/reports`,
        REPORTS_RECENT:  `${API_BASE_URL}/admin/reports/recent`,
        REPORT_REASONS:  `${API_BASE_URL}/admin/report-reasons`,
        HEATMAP:       `${API_BASE_URL}/admin/heatmap`,
        FUNNEL:        `${API_BASE_URL}/admin/funnel`,
        DISTRIBUTIONS: `${API_BASE_URL}/admin/distributions`,

        UPDATE_REPORT:         (id: number | string) => `${API_BASE_URL}/admin/reports/${id}`,
        CHALLENGES_MANAGE:     `${API_BASE_URL}/admin/challenges/manage`,
        CHALLENGES_EXPORT:     `${API_BASE_URL}/admin/challenges/export`,
        CHALLENGES_IMPORT:     `${API_BASE_URL}/admin/challenges/import`,
        CHALLENGES_GENERATE_AI:`${API_BASE_URL}/admin/challenges/generate-ai`,
        CHALLENGE_UPDATE:      (id: number | string) => `${API_BASE_URL}/admin/challenges/${id}`,
        CHALLENGE_HIDDEN:      (id: number | string) => `${API_BASE_URL}/admin/challenges/${id}/hidden`,
        CHALLENGE_DETAIL:      (id: number | string) => `${API_BASE_URL}/admin/challenges/${id}/detail`,
        CHALLENGE_DIFFICULTY:  (id: number | string) => `${API_BASE_URL}/admin/challenges/${id}/difficulty`,
        CHALLENGE_DELETE:      (id: number | string) => `${API_BASE_URL}/admin/challenges/${id}`,
        TOPICS:                `${API_BASE_URL}/admin/topics`,
        TOPIC:                 (id: number | string) => `${API_BASE_URL}/admin/topics/${id}`,
        LEADERBOARD:           `${API_BASE_URL}/users/leaderboard`,
        ACHIEVEMENTS:          `${API_BASE_URL}/admin/achievements`,
        ACHIEVEMENT:           (id: number | string) => `${API_BASE_URL}/admin/achievements/${id}`,
        CODEWARS_KATA:         (id: string) => `${API_BASE_URL}/admin/codewars/kata/${encodeURIComponent(id)}`,
        TEST_STATS:            `${API_BASE_URL}/admin/test-stats`,
    },
    TESTS: {
        // Справочник
        QUESTION_TYPES:       `${API_BASE_URL}/tests/question-types`,
        RUN_CODE:             `${API_BASE_URL}/tests/run-code`,
        RUN_CODE_PREVIEW:     `${API_BASE_URL}/tests/run-code-preview`,

        // Пользователь
        LIST:                 `${API_BASE_URL}/tests`,
        ONE:                  (id: number | string) => `${API_BASE_URL}/tests/${id}`,
        START:                (id: number | string) => `${API_BASE_URL}/tests/${id}/start`,
        SUBMIT:               (attemptId: number | string) => `${API_BASE_URL}/tests/attempts/${attemptId}/submit`,
        MY_ATTEMPTS:          (id: number | string) => `${API_BASE_URL}/tests/${id}/my-attempts`,
        ATTEMPT_RESULT:       (attemptId: number | string) => `${API_BASE_URL}/tests/attempts/${attemptId}/result`,
        REPORT_REASONS:       (id: number | string) => `${API_BASE_URL}/tests/${id}/report-reasons`,
        REPORT:               (id: number | string) => `${API_BASE_URL}/tests/${id}/report`,
        REVIEWS:              (id: number | string) => `${API_BASE_URL}/tests/${id}/reviews`,

        // Админ
        ADMIN_LIST:           `${API_BASE_URL}/tests/admin/tests`,
        ADMIN_ONE:            (id: number | string) => `${API_BASE_URL}/tests/admin/tests/${id}`,
        ADMIN_CREATE:         `${API_BASE_URL}/tests/admin/tests`,
        ADMIN_UPDATE:         (id: number | string) => `${API_BASE_URL}/tests/admin/tests/${id}`,
        ADMIN_PUBLISH:        (id: number | string) => `${API_BASE_URL}/tests/admin/tests/${id}/publish`,
        ADMIN_DELETE:         (id: number | string) => `${API_BASE_URL}/tests/admin/tests/${id}`,
        ADMIN_EXPORT:         (id: number | string) => `${API_BASE_URL}/tests/admin/tests/${id}/export`,
        ADMIN_IMPORT:         `${API_BASE_URL}/tests/admin/tests/import`,
        ADMIN_IMPORT_QUIZ:    `${API_BASE_URL}/tests/admin/tests/import-quiz`,

        // Вопросы (админ)
        QUESTION_CREATE:      (testId: number | string) => `${API_BASE_URL}/tests/admin/tests/${testId}/questions`,
        QUESTION_UPDATE:      (testId: number | string, qId: number | string) => `${API_BASE_URL}/tests/admin/tests/${testId}/questions/${qId}`,
        QUESTION_DELETE:      (testId: number | string, qId: number | string) => `${API_BASE_URL}/tests/admin/tests/${testId}/questions/${qId}`,
        QUESTION_REORDER:     (testId: number | string) => `${API_BASE_URL}/tests/admin/tests/${testId}/questions/reorder`,
        QUESTION_IMAGE:       (qId: number | string) => `${API_BASE_URL}/tests/admin/questions/${qId}/image`,
    },
    SOLUTION: {
        VOTES:      (id: number | string) => `${API_BASE_URL}/solutions/${id}/votes`,
        COMMENTS:   (id: number | string) => `${API_BASE_URL}/solutions/${id}/comments`,
        COMMENT:    (id: number | string, commentId: number | string) => `${API_BASE_URL}/solutions/${id}/comments/${commentId}`,
    },
    NOTIFICATIONS: {
        GET:        `${API_BASE_URL}/users/notifications`,
        READ:       (id: number | string) => `${API_BASE_URL}/users/notifications/${id}/read`,
        DELETE_ONE: (id: number | string) => `${API_BASE_URL}/users/notifications/${id}`,
        DELETE_ALL: `${API_BASE_URL}/users/notifications`,
    },
};
